# Generated by Django 4.0.2 on 2022-02-28 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_component', models.CharField(max_length=255)),
                ('label_of_component', models.CharField(max_length=255)),
                ('is_disposed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('anydesk_id', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.png', upload_to='uploads/')),
                ('note', models.TextField(default='Text here')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('WORKING', 'WORKING'), ('TO_BE_REPAIRED', 'TO_BE_REPAIRED'), ('BROKEN', 'BROKEN')], max_length=30)),
                ('is_disposed', models.BooleanField(default=False)),
                ('components', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.component')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_consumables', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.staff')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.staff'),
        ),
    ]
