# Generated by Django 4.0.3 on 2022-03-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
