# Generated by Django 4.0.2 on 2022-02-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='components',
        ),
        migrations.AddField(
            model_name='equipment',
            name='components',
            field=models.ManyToManyField(null=True, to='equipment.Component'),
        ),
    ]
