# Generated by Django 3.2.8 on 2021-12-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_disposed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('WORKING', 'WORKING'), ('TO_BE_REPAIRED', 'TO_BE_REPAIRED'), ('BROKEN', 'BROKEN')], default='default', max_length=30),
            preserve_default=False,
        ),
    ]
