# Generated by Django 4.0.3 on 2022-03-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_component_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='components',
            field=models.ManyToManyField(blank=True, to='equipment.component'),
        ),
    ]
