# Generated by Django 4.0.2 on 2022-02-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_components_equipment_components'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='label_of_component',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='component',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.staff'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.staff'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='components',
            field=models.ManyToManyField(to='equipment.Component'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.staff'),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.staff'),
        ),
    ]
