# Generated by Django 4.0.3 on 2022-03-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='asset_tag',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
