# Generated by Django 4.0.2 on 2022-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_rename_label_of_component_component_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
