# Generated by Django 4.0.3 on 2022-03-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_component_asset_tag_alter_equipment_asset_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='asset_tag',
            field=models.CharField(blank=True, default='SHAP', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.component'),
        ),
    ]
