# Generated by Django 4.0.2 on 2022-02-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_component_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
