# Generated by Django 4.0.2 on 2022-02-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_license_delete_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='license',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
