# Generated by Django 4.0.2 on 2022-02-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_remove_license_quantity_alter_equipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='expiring',
            new_name='is_assigned',
        ),
        migrations.AddField(
            model_name='component',
            name='model_number',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
