# Generated by Django 4.0.3 on 2022-03-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_component_asset_tag_alter_equipment_asset_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='asset_tag',
            field=models.CharField(default='SHAP', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(default='SHAP', max_length=30, null=True, unique=True),
        ),
    ]
