# Generated by Django 3.2.8 on 2021-11-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20211110_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='updated_at',
        ),
    ]
